QuotesReader.Infrastructure.Web/Models/ErrorViewModel.cs
namespace QuotesReader.Infrastructure.Web.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

QuotesReader.Infrastructure.Web/Controllers/QuoteController.cs
using Microsoft.AspNetCore.Mvc;

namespace QuotesReader.Infrastructure.Web.Controllers;

public class QuoteController : Controller
{
    private readonly ILogger<QuoteController> _logger;
    private readonly WebAdapter _adapter;

    public QuoteController(ILogger<QuoteController> logger, WebAdapter adapter)
    {
        _logger = logger;
        _adapter = adapter;
    }

    public IActionResult Index()
    {
        var quote = _adapter.RequestQuote();

        return View(quote);
    }
}

QuotesReader.Infrastructure.Web/Views/Quote/Index.cshtml
@model QuotesReader.Infrastructure.Common.ViewModels.QuoteViewModel

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>@Model.Quote</p>
</div>

QuotesReader.Infrastructure.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - QuotesReader</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Quote" asp-action="Index">QuotesReader</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Quote" asp-action="Index">Home</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>